version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: myapp:latest
    container_name: myapp
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_REDIS_HOST=host.docker.internal
      - SPRING_REDIS_PORT=6379
